<a href="https://colab.research.google.com/github/kidrah-git/my_repo/blob/master/Copy_of_00_fundamentals_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import tenorflow
import tensorflow as tf
print(tf. __version__)

2.15.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of deimension of a tensor
scalar.ndim


0

In [ ]:
#creating a vector
vector = tf.constant ([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check the dimension of the vector
vector.ndim

1

In [ ]:
# create a Matrix
matrix = tf.constant ([[10, 7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# specify the data type
another_matrix = tf.constant ([[10., 5.], [5., 10.], [7., 10.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  5.],
       [ 5., 10.],
       [ 7., 10.]], dtype=float16)>

In [ ]:
# whats the number of dimension of another matrix
another_matrix.ndim

2

In [ ]:
# lets create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [2, 3, 4 ],
                      [ 5, 6, 7],
                      [3, 4, 6],
                       [2, 3, 5],
                       [4, 6, 7]]])
tensor

<tf.Tensor: shape=(1, 6, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 3, 4],
        [5, 6, 7],
        [3, 4, 6],
        [2, 3, 5],
        [4, 6, 7]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
#creating tensor with tf.Variable
changeable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])

changeable_tensor, unchangable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# how about creating the changable tensor into .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>