<a href="https://colab.research.google.com/github/kidrah-git/my_repo/blob/master/Copy_of_00_fundamentals_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#import tenorflow
import tensorflow as tf
print(tf. __version__)

2.15.0


In [5]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# check the number of deimension of a tensor
scalar.ndim


0

In [7]:
#creating a vector
vector = tf.constant ([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
#check the dimension of the vector
vector.ndim

1

In [9]:
# create a Matrix
matrix = tf.constant ([[10, 7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
# specify the data type
another_matrix = tf.constant ([[10., 5.], [5., 10.], [7., 10.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  5.],
       [ 5., 10.],
       [ 7., 10.]], dtype=float16)>

In [ ]:
# whats the number of dimension of another matrix
another_matrix.ndim

2

In [12]:
# lets create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [2, 3, 4 ],
                      [ 5, 6, 7],
                      [3, 4, 6],
                       [2, 3, 5],
                       [4, 6, 7]]])
tensor

<tf.Tensor: shape=(1, 6, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 3, 4],
        [5, 6, 7],
        [3, 4, 6],
        [2, 3, 5],
        [4, 6, 7]]], dtype=int32)>

In [13]:
tensor.ndim

3

In [14]:
#creating tensor with tf.Variable
changeable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])

changeable_tensor, unchangable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
# how about creating the changable tensor into .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [24]:
# creating random tensors
# creating two random with the same tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproductibility
random_1 = random_1.normal (shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal (shape=(3,2))

# are random_1 and random_2 equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [31]:
### shuffle the order of the elements in the tensor


not_shuffle = tf.constant ([[10,  6], [7, 10], [5, 3]])





In [32]:
# shuffle our non shuffled tenors
tf.random.shuffle(not_shuffle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [10,  6],
       [ 5,  3]], dtype=int32)>

In [34]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffle, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  6],
       [ 7, 10],
       [ 5,  3]], dtype=int32)>

In [35]:
not_shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  6],
       [ 7, 10],
       [ 5,  3]], dtype=int32)>